# generated by datamodel-codegen:
#   filename:  input_schema.json
#   timestamp: 2026-08-04T06:22:32+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class OpenaiVectorStoreIntegration(BaseModel):
    vectorStoreId: str = Field(
        ...,
        description='Vector Store ID where the data will be stored',
        title='Vector Store ID',
    )
    openaiApiKey: str = Field(..., description='OpenAI API KEY', title='OpenAI API KEY')
    assistantId: Optional[str] = Field(
        None,
        description="Deprecated and ignored. Previously used to look up an OpenAI Assistant's model for token counting when splitting large files. The OpenAI Assistants API is being retired (shutdown on 2026-08-26); this Actor no longer calls it. Splitting oversized files into smaller segments now happens automatically, regardless of this field. Kept only so previously saved inputs/integrations that set it continue to validate; you can safely remove it.",
        title='Assistant ID (deprecated, unused)',
    )
    datasetFields: List = Field(
        ...,
        description='A list of dataset fields which should be selected from the items, only these dataset fields will remain in the resulting record objects.\n\n For example, when using the website content crawler, you might select dataset fields such as `text` and `url`, and `metadata.title` among others, to be included in the vector store file.',
        title='A list of dataset fields which should be selected from the dataset',
    )
    filePrefix: Optional[str] = Field(
        None,
        description="Using a file prefix helps with the management of vector store file updates by eliminating the need to track each file's ID. For instance, if you set the filePrefix to 'apify-advisor', the Actor will initially locate all files in the vector store with this prefix. Subsequently, it will delete these files and create new ones, also prefixed accordingly.",
        min_length=5,
        title='Delete/Create vector store files with a prefix',
    )
    fileIdsToDelete: Optional[List] = Field(
        None,
        description='Delete specified file ids associated with vector store. This can be useful when one needs to delete files that are no longer needed.',
        title='Array of vector store file ids to delete',
    )
    saveCrawledFiles: Optional[bool] = Field(
        True,
        description="Save files from Apify's key-value store to OpenAI's file store. Useful when utilizing Apify’s website content crawler with the 'saveFiles' option, allowing the found files to be directly stored.",
        title='Save crawled files (docs, pdf, pptx) to OpenAI File Store',
    )
    datasetId: Optional[str] = Field(
        None,
        description='The Dataset ID is provided automatically when the actor is set up as an integration. You can fill it in explicitly here to enable debugging of the actor',
        title="Apify's Dataset ID",
    )
    keyValueStoreId: Optional[str] = Field(
        None,
        description='This is the ID for the Key-value store on Apify, which serves as the data source for json, pdf, and pptx files. This ID is automatically provided when the actor is integrated. However, you can manually enter the ID here for debugging purposes.',
        title="Apify's Key-value store ID (source for json, pdf, pptx files) ",
    )
    saveInApifyKeyValueStore: Optional[bool] = Field(
        False,
        description="Save all created files in the Apify's Key-Value Store to easily check and retrieve all files (this is typically used when debugging)",
        title="Save all created files in the Apify's key-value store",
    )
